server:
  port: 9200
spring:
  application:
    name: services-showtimes
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:showtimeBD;
    driver-class-name: org.h2.Driver
    platform: h2
    data-username: sa
    data-password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

