server:
   port: 9100
spring:
    application:
      name: services-users
    h2:
      console:
        enabled: true
    datasource:
        url: jdbc:h2:mem:usersBD;
        driver-class-name: org.h2.Driver
        platform: h2
        data-username: sa
        data-password:
    jpa:
       show-sql: true
       database-platform: org.hibernate.dialect.H2Dialect
